WIP: Update ember version to 3.10
adfinis-sygroup/ember-autolinker pull request #3
Opened 2019-05-21 15:51 UTC by velrest

2019-05-22 05:36 UTC, anehx requested changes

2019-05-22 05:36 UTC, anehx commented on .travis.yml
> -  - bash <(curl -s https://codecov.io/bash)
This is missing

2019-05-28 14:15 UTC, velrest commented on .travis.yml
> -  - bash <(curl -s https://codecov.io/bash)
Fixed :+1:

2019-05-29 05:26 UTC, anehx requested changes
Prettier

2019-05-29 05:26 UTC, anehx commented on .eslintrc.js
> +  ],
Prettier is missing, also don't forget to run `yarn lint:js --fix` after adding it in the config..

2020-11-30 13:11 UTC, closed without merging